name: CI/CD

on:
  push:
    branches:
      - feat/be/mock-data
env:
  working-directory: ./be
  DOCKER_IMAGE: gamja
  DOCKER_REGISTRY: gamja123
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  EC2_HOST: <EC2 인스턴스 IP>
  EC2_USERNAME: <EC2 인스턴스 사용자 이름>
  SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build and push Docker image
        with:
          context: .
          dockerfile: be/Dockerfile
          push: true
        run: |
          docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE -f Dockerfile .
          docker push $DOCKER_REGISTRY/$DOCKER_IMAGE

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy SSH key to EC2 instance
        run: |
          ssh-copy-id -i "${{ secrets.SSH_KEY }}" ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}

      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          script: |
            docker pull ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_IMAGE }}
            docker run -d ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_IMAGE }}