name: CI/CD

on:
  push:
    branches:
      - feat/be/mock-data
env:
  working-directory: ./be
  DOCKER_IMAGE: gamja
  DOCKER_REGISTRY: gamja123
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean build
        working-directory: ./be

      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build and push Docker image
        working-directory: ./be
        run: |
          docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE .
          docker push $DOCKER_REGISTRY/$DOCKER_IMAGE

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker-compose down --volumes --remove-orphans
            sudo docker image prune -a --force 
            docker pull ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_IMAGE }}
            docker pull ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_IMAGE }}/second-hand-nginx
            docker-compose up -d
            docker image prune -f